### ISSUE TITLE
XCode palette

### ISSUE THREAD

**Issue by gyetvan-andras** [NorthernRealities/Rainbow#1]
Hello, your work is really impressing! 
It is just an idea, but I think it worths a look: make all your colors available as a color picker palette. If you think, there are few links:
- [Adding Custom Color Pickers to a Color Panel](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/DrawColor/Tasks/AddingColorPickers.html)
- [NSColorList](https://developer.apple.com/library/mac/documentation/Cocoa/Reference/ApplicationKit/Classes/NSColorList_Class/index.html)
- [FlatUI Color Picker](https://github.com/hemantasapkota/FlatUIColorPaletteXCode)

Also, I have created a similar color ~~palette~~ library (see: [CWColors](https://github.com/gyetvan-andras/Chart.js-ObjC-Wrapper#cwcolors-library) ) where I added a function to randomly picks a color, which is used to select a color for a chart, where the chart content cannot be determined at compile time.

**Comment by NorthernRealities** [comment]
Hi,

Thanks for your message.  It’s a great idea and I didn’t even know that you could do this. I’m going to look into it though I don’t know how soon I’ll be able to do it.  I’ve never made anything for the Mac.  Actually I’m just learning how to make iOS apps.  I’m also looking into supporting CocoaPods and Carthage with the library.

Thanks for the link to the library.

Reid.

**Comment by gyetvan-andras** [comment]
Thanks, it is really just an idea, which came into my mind, when I read that you want to create an app to select colors from your lib. But what could be better than make your colors accessible from XCode?
And, it is my mistake, that I wrote "_I created a_ **_palette**_", but it is just a library, similar to yours.

**Comment by NorthernRealities** [comment]
Hi,

I’ve just added the palettes up onto a new repository called Rainbow-Palettes which you can find at https://github.com/NorthernRealities/Rainbow-Palettes https://github.com/NorthernRealities/Rainbow-Palettes  Sorry it took a while to get to it.  I was writing a new version of the Xcode plugin which displays the colour when you place the carat over some code that creates a NSColor or UIColor.  That’s up on GitHub too under the ColorSenseRainbow repository in case you are interested.  Like the original it allows you to change your code by choosing the colour from the picker.  

Thanks again for the idea,
Reid.

**Comment by wdcurry** [comment]
cool thinking folks, and this is late to the game. My thinking differs somewhat, and it seems more challenging to accomplish within Swift: enable the auto extraction/reflection of all the available colours within a running app, to allow the user to select a color from within the extensions provided. So far, not generating much in the way of ideas except for manually creating an array of UIColors with associated index within the repo.
